env:
  browser: true
  es6: true
globals:
  $: false
extends: 'eslint:recommended'
rules:
  indent: off
  linebreak-style:
    - error
    - unix
  quotes: off
  no-console: off
  semi:
    - error
    - never
  consistent-return: warn
  curly:
    - error
    - multi-or-nest
    - consistent
  eqeqeq:
    - error
    - always
  no-unused-vars:
    - error
    -
      args: none
  no-case-declarations: warn
  no-eval: error
  no-proto: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: warn
  no-useless-call: warn
  no-useless-return: warn
  no-void: error
  prefer-promise-reject-errors: error
  strict:
    - error
    - global
  no-label-var: error
  no-lonely-if: off
  no-new-object: error

